# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=32)),
                ('start', models.DateTimeField()),
                ('expire', models.DateTimeField()),
                ('down', models.DateTimeField()),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.User'),
        ),
    ]
